server:
  port: '8443'
  ssl:
    bundle: server
    enabled:
      protocols: 'TLSv1.3,TLSv1.2'
spring:
  main:
    banner-mode: OFF
    log-startup-info: OFF
  ssl:
    bundle:
      pem:
        server:
          keystore:
            certificate: /opt/vss/ext/tls/cert.pem
            private-key: /opt/vss/ext/tls/key.pem
  application:
    name: VSS
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
service:
  policies:
    uri: >-
      https://raw.githubusercontent.com/grandamp/rest-service/refs/heads/main/configuration/policies.json
  intermediates:
    uri: >-
      https://www.idmanagement.gov/implement/tools/CACertificatesValidatingToFederalCommonPolicyG2.p7b
  systemlog:
    enabled: false
    file: /opt/vss/ext/logs/system.log
  validation:
    pkix:
# If AIA Chase is enabled, `max-path-length` *might* be ignored
# Otherwise, `max-path-length` will be enforced, and the only intermediates that will be considered will be certs in the CMS CERTS-ONLY file defined via `service.intermediates.uri`
      aia-chase: false
      max-path-length: 7
      revocation-enabled: true
      revocation-ee-only: true
      ocsp-enabled: true
      crl-enabled: true
logging:
  pattern:
    console: "{\"time\": \"%d\", \"level\": \"%p\", \"class\": \"%logger{63}:%L\", \"message\": %m}%n"
    file: "{\"time\": \"%d\", \"level\": \"%p\", \"class\": \"%logger{63}:%L\", \"message\": %m}%n"
  level:
    org.apache.catalina.core: OFF
    org.springframework: OFF
    org.springdoc.api.AbstractOpenApiResource: OFF
    org.keysupport.api.controller.vss.ValidateController.validateV1: ERROR
  file:
    name: /opt/vss/ext/logs/vss.log
  logback:
    rollingpolicy:
      file-name-pattern: 'vss-%d{yyyy-MM-dd}.%i.log'
      max-file-size: 10MB
      max-history: 7
springdoc:
  swagger-ui:
    enabled: true
    use-root-path: true
